### ISSUE TITLE
mmm-mode package dependency issue

### ISSUE THREAD

**Issue by alan-cugler** [nixjdm/emacs.d#11]
When opening any file the following message pops up from buffer:
```
Warning (emacs): Unable to activate package `salt-mode'.                        
Required package `mmm-mode-0.5.4' is unavailable                                
Warning (emacs): Unable to activate package `mmm-jinja2'.                       
Required package `mmm-mode-0.5.4' is unavailable                                
Warning (emacs): Unable to activate package `salt-mode'.                        
|Required package `mmm-mode-0.5.4' is unavailable                                
Warning (emacs): Unable to activate package `mmm-jinja2'.                       
Required package `mmm-mode-0.5.4' is unavailable
```
I ran the following terminal search `grep -R --exclude-dir="archives/" "mmm-mode" .emacs.d/`
and from this it shows `mmm-mode-0.5.6` is installed but some salt $ jinja2 packages seem to be saying `mmm-mode-0.5.4` is a required package as a hard dependency.

Bottom chunk of grep search output:
```
.emacs.d/elpa/salt-mode-20180118.1754/salt-mode-pkg.el:(define-package "salt-mode" "20180118.1754" "Major mode for Salt States" '((emacs "24.4") (yaml-mode "0.0.12") (mmm-mode "0.5.4") (mmm-jinja2 "0.1")) :commit "e46c28ef77663391519646c79641c9d177f70d35" :keywords '("languages") :url "https://github.com/glynnforrest/salt-mode")
.emacs.d/elpa/salt-mode-20180118.1754/salt-mode.el:;; Package-Requires: ((emacs "24.4") (yaml-mode "0.0.12") (mmm-mode "0.5.4") (mmm-jinja2 "0.1"))
.emacs.d/elpa/salt-mode-20180118.1754/salt-mode.el:;; Syntax highlighting: Fontification supports YAML & Jinja using mmm-mode
.emacs.d/elpa/salt-mode-20180118.1754/salt-mode.el:;; Tag complete: Using mmm-mode you can generate insert templates:
.emacs.d/elpa/mmm-jinja2-20170313.720/mmm-jinja2-pkg.el:(define-package "mmm-jinja2" "20170313.720" "MMM submode class for Jinja2 Templates" '((mmm-mode "0.5.4")) :commit "c8cb763174fa2fb61b9a0e5e0ff8cb0210f8492f" :url "https://github.com/glynnforrest/mmm-jinja2")
.emacs.d/elpa/mmm-jinja2-20170313.720/mmm-jinja2.el:;; Package-Requires: ((mmm-mode "0.5.4"))
```

**Comment by alan-cugler** [comment]
https://stackoverflow.com/questions/23749267/how-do-i-disable-warnings-at-initialization-in-emacs

I used this above resource to "silence" the annoying popup until this issue gets fixed. 
Just add this line to the init.el file and problem brushed under the rug:
`(setq warning-minimum-level :error)`

**Comment by nixjdm** [comment]
I have seen this before. I don't think I am now though for some reason. I think I see it once and then it goes away after my packages are updated?

This seems more like an upstream problem with `salt-mode`.

**Comment by nixjdm** [comment]
salt-mode definitely requires the older version of mmm-mode, so one solution is for use to actually manually grab that and include it. Another would be to fix salt-mode.

The reason I only see this occasionally is because I use emacsclient. I only see it when restarting my client which is rare.
