### ISSUE TITLE
Space highlighting in files

### ISSUE THREAD

**Issue by alan-cugler** [nixjdm/emacs.d#7]
Working on Django2.1 project with python 3.6.6 and my .py files are having preappending white space highlighted.

example:
#Code with "_" is the highlighted white space.

```
TEMPLATES = [
_    {
_    _    'BACKEND': 'django.template.backends.django.DjangoTemplates',
_    _    'DIRS': [],
_    _    'APP_DIRS': True,
_    _    'OPTIONS': {
_    _    _    'context_processors': [
_    _    _    _    'django.template.context_processors.debug',
_    _    _    _    'django.template.context_processors.request',
_    _    _    _    'django.contrib.auth.context_processors.auth',
_    _    _    _    'django.contrib.messages.context_processors.messages',
_    _    _    ],
_    _    },
_    },
]
```

**Comment by alan-cugler** [comment]
https://github.com/antonj/Highlight-Indentation-for-Emacs

**Comment by alan-cugler** [comment]
in ~/.emacs.d/custom.el
you have "'(highlight-indentation-face ((t nil)))"
on line 66.

**Comment by alan-cugler** [comment]
disabled the highlighting of indentations by this:

M-x to open buffer
typed `highlighting-indentation-mode`
This toggles the feature on/off but doesn't make it permanent.

**Comment by alan-cugler** [comment]
tried to permanently shut off highlight indentation by going to `~/.emacs.d/elpa/elpy-[hash]/elpy.el` and 
commenting out lines 79, 95, and 96. So far seems to work.

**Comment by nixjdm** [comment]
I'm pretty sure this is why I added https://github.com/nixjdm/emacs.d/blob/master/init.el#L117. I don't think I've seen any indentation highlighting since. It's not working for you, I suppose.

**Comment by nixjdm** [comment]
This should have been fixed by https://github.com/nixjdm/emacs.d/blob/2088ebbc226a0f5ab2252682f8013c333ca51433/init.el#L117

See https://stackoverflow.com/questions/45214116/how-to-disable-emacs-elpy-vertical-guide-lines-for-indentation The chosen theme changes how the highlighting works, btw.
